= Assets
:nofooter:

[plantuml, target=tree_example, format=svg, width=100%]
....
@startuml
skinparam defaultFontName JetBrains Mono

left to right direction
' Horizontal lines: -->, <--, <-->
' Vertical lines: ->, <-, <->

map Mult {
}

map Subtract {
}

map 2 {
}

map Add {
}

map x {
}

map 5 {
}

Mult --> Subtract
Mult --> 2

Subtract --> Add

Add --> x
Add --> 5

@enduml
....

[plantuml, target=token_id, format=svg, width=100%]
....
@startuml
skinparam defaultFontName JetBrains Mono

[*] --> ID
ID --> [*]
ID : char { char, digit, '-' } 

ID -> ID

@enduml
....

[plantuml, target=token_integer, format=svg, width=100%]
....
@startuml
skinparam defaultFontName JetBrains Mono

[*] --> integer
integer --> [*]
integer : char { digit }

integer -> integer

@enduml
....

[plantuml, target=class_integer, format=svg, width=100%]
....
@startuml
skinparam defaultFontName JetBrains Mono

class Integer {
  int 457
}

@enduml
....

[plantuml, target=class_id, format=svg, width=100%]
....
@startuml
skinparam defaultFontName JetBrains Mono

class Id {
  string "value"
}

@enduml
....

[plantuml, target=abstract_treenode, format=svg, width=100%]
....
@startuml
skinparam defaultFontName JetBrains Mono

abstract TreeNode

@enduml
....

[plantuml, target=class_add, format=svg, width=100%]
....
@startuml
skinparam defaultFontName JetBrains Mono

class Add {
  treeNode	*left;
  treeNode	*right;
}

@enduml
....

[plantuml, target=class_subtract, format=svg, width=100%]
....
@startuml
skinparam defaultFontName JetBrains Mono

class Subtract {
  treeNode	*left;
  treeNode	*right;
}

@enduml
....

[plantuml, target=class_mult, format=svg, width=100%]
....
@startuml
skinparam defaultFontName JetBrains Mono

class Mult {
  treeNode	*left;
  treeNode	*right;
}

@enduml
....

[plantuml, target=class_div, format=svg, width=100%]
....
@startuml
skinparam defaultFontName JetBrains Mono

class  Div {
  treeNode	*left;
  treeNode	*right;
}

@enduml
....

[plantuml, target=class_negate, format=svg, width=100%]
....
@startuml
skinparam defaultFontName JetBrains Mono

class Negate {
  treeNode	*arg;
}

@enduml
....
