= Assets
:nofooter:

[plantuml, target=tree_example, format=svg, width=100%]
....
@startuml
skinparam defaultFontName JetBrains Mono

left to right direction
' Horizontal lines: -->, <--, <-->
' Vertical lines: ->, <-, <->

map Mult {
}

map Subtract {
}

map 2 {
}

map Add {
}

map x {
}

map 5 {
}

Mult --> Subtract
Mult --> 2

Subtract --> Add

Add --> x
Add --> 5

@enduml
....

[plantuml, target=token_id, format=svg, width=100%]
....
@startuml
skinparam defaultFontName JetBrains Mono

[*] --> ID
ID --> [*]
ID : char { char, digit, '-' } 

ID -> ID

@enduml
....

[plantuml, target=token_integer, format=svg, width=100%]
....
@startuml
skinparam defaultFontName JetBrains Mono

[*] --> integer
integer --> [*]
integer : char { digit }

integer -> integer

@enduml
....

[plantuml, target=class_integer, format=svg, width=100%]
....
@startuml
skinparam defaultFontName JetBrains Mono

class Integer {
  int 457
}

@enduml
....

[plantuml, target=class_id, format=svg, width=100%]
....
@startuml
skinparam defaultFontName JetBrains Mono

class Id {
  string "value"
}

@enduml
....

[plantuml, target=abstract_treenode, format=svg, width=100%]
....
@startuml
skinparam defaultFontName JetBrains Mono

abstract TreeNode

@enduml
....

[plantuml, target=class_add, format=svg, width=100%]
....
@startuml
skinparam defaultFontName JetBrains Mono

class Add {
  treeNode	*left;
  treeNode	*right;
}

@enduml
....

[plantuml, target=class_subtract, format=svg, width=100%]
....
@startuml
skinparam defaultFontName JetBrains Mono

class Subtract {
  treeNode	*left;
  treeNode	*right;
}

@enduml
....

[plantuml, target=class_mult, format=svg, width=100%]
....
@startuml
skinparam defaultFontName JetBrains Mono

class Mult {
  treeNode	*left;
  treeNode	*right;
}

@enduml
....

[plantuml, target=class_div, format=svg, width=100%]
....
@startuml
skinparam defaultFontName JetBrains Mono

class  Div {
  treeNode	*left;
  treeNode	*right;
}

@enduml
....

[plantuml, target=class_negate, format=svg, width=100%]
....
@startuml
skinparam defaultFontName JetBrains Mono

class Negate {
  treeNode	*arg;
}

@enduml
....

[plantuml, target=program_class, format=svg, width=100%]
....
@startuml
skinparam defaultFontName JetBrains Mono

abstract TreeNode {
  == public ==
  .. Member ..
  TreeNode(void);
  +~TreeNode(void);
  .. virtual ..
  +{abstract} int	eval(void) = 0;
  +{abstract} void	print(void) = 0;
  +{abstract} void	result(void) = 0;
  .. setter ..
  +void set_left(int const &);
  +void set_left(TreeNode *);
  +void set_right(int const &);
  +void set_right(TreeNode *);
  .. getter ..
  +TreeNode &get_left(void);
  +TreeNode &get_right(void);
  .. exception ..
  +NodeAlreadyDefine
  +NullPointerNode
  .. operator << ..
  std::cout << node.eval();
  == private ==
  TreeNode	*_left;
  TreeNode	*_right;
}
note right of TreeNode::~TreeNode
  Free left and right tree nodes
end note
abstract Infix {
  == public ==
  {abstract} char getSymbole(void) const = 0;
}

class Add {
  == public ==
  .. Member ..
  +Add(void);
  +~Add(void);
  .. other ..
  +int eval(void);
  +void print(void);
  +void result(void);
  +char getSymbole(void) const;
  .. operator << ..
  std::cout << node.eval();
}
note right of Add::eval
  left->eval() + right->eval()
end note

class Mult {
  == public ==
  .. Member ..
  +Mult(void);
  +~Mult(void);
  .. other ..
  +int eval(void);
  +void print(void);
  +void result(void);
  +char getSymbole(void) const;
  .. operator << ..
  std::cout << node.eval();
}

class Div {
  == public ==
  .. Member ..
  +Div(void);
  +~Div(void);
  .. other ..
  +int eval(void);
  +void print(void);
  +void result(void);
  +char getSymbole(void) const;
  .. operator << ..
  std::cout << node.eval();
}

class Subtract {
  == public ==
  .. Member ..
  +Subtract(void);
  +~Subtract(void);
  .. other ..
  +int eval(void);
  +void print(void);
  +void result(void);
  +char getSymbole(void) const;
  .. operator << ..
  std::cout << node.eval();
}

class Number {
  == public ==
  +void print(void);
  +void set_number(int);
  +int eval(void);
  == private ==
  int	_number;
}

TreeNode <|-- Infix
TreeNode <|-- Number
Infix <|-- Add
Infix <|-- Subtract
Infix <|-- Mult
Infix <|-- Div

@enduml
....

[plantuml, target=parse_token, format=svg, width=100%]
....
@startuml
skinparam defaultFontName JetBrains Mono

[*] --> priorityOne
priorityOne --> priorityOne : ! EOS
priorityOne -> find : find
find -> priorityOne

priorityOne --> priorityZero : EOS, start again the input
priorityZero --> priorityZero : ! EOS
priorityZero -> find : find
find -> priorityZero
priorityZero --> [*]

find: Find an operator as node\nset left with (index - 1) and\nset right with (index + 1)\nerase left and right of the stack pointer
priorityOne: An operator "*" and a number
priorityZero: An operator "+/-" and a number

@enduml
....
