= Assets
:nofooter:

[plantuml, target=tree_example, format=svg, width=100%]
....
@startuml
skinparam defaultFontName JetBrains Mono

left to right direction
' Horizontal lines: -->, <--, <-->
' Vertical lines: ->, <-, <->

map Mult {
}

map Subtract {
}

map 2 {
}

map Add {
}

map x {
}

map 5 {
}

Mult --> Subtract
Mult --> 2

Subtract --> Add

Add --> x
Add --> 5

@enduml
....

[plantuml, target=token_id, format=svg, width=100%]
....
@startuml
skinparam defaultFontName JetBrains Mono

[*] --> ID
ID --> [*]
ID : char { char, digit, '-' } 

ID -> ID

@enduml
....

[plantuml, target=token_integer, format=svg, width=100%]
....
@startuml
skinparam defaultFontName JetBrains Mono

[*] --> integer
integer --> [*]
integer : char { digit }

integer -> integer

@enduml
....

[plantuml, target=class_integer, format=svg, width=100%]
....
@startuml
skinparam defaultFontName JetBrains Mono

class Integer {
  int 457
}

@enduml
....

[plantuml, target=class_id, format=svg, width=100%]
....
@startuml
skinparam defaultFontName JetBrains Mono

class Id {
  string "value"
}

@enduml
....

[plantuml, target=abstract_treenode, format=svg, width=100%]
....
@startuml
skinparam defaultFontName JetBrains Mono

abstract TreeNode

@enduml
....

[plantuml, target=class_add, format=svg, width=100%]
....
@startuml
skinparam defaultFontName JetBrains Mono

class Add {
  treeNode	*left;
  treeNode	*right;
}

@enduml
....

[plantuml, target=class_subtract, format=svg, width=100%]
....
@startuml
skinparam defaultFontName JetBrains Mono

class Subtract {
  treeNode	*left;
  treeNode	*right;
}

@enduml
....

[plantuml, target=class_mult, format=svg, width=100%]
....
@startuml
skinparam defaultFontName JetBrains Mono

class Mult {
  treeNode	*left;
  treeNode	*right;
}

@enduml
....

[plantuml, target=class_div, format=svg, width=100%]
....
@startuml
skinparam defaultFontName JetBrains Mono

class  Div {
  treeNode	*left;
  treeNode	*right;
}

@enduml
....

[plantuml, target=class_negate, format=svg, width=100%]
....
@startuml
skinparam defaultFontName JetBrains Mono

class Negate {
  treeNode	*arg;
}

@enduml
....

[plantuml, target=program_class, format=svg, width=100%]
....
@startuml
skinparam defaultFontName JetBrains Mono

abstract TreeNode {
  .. public ..
  +{abstract} int eval(void) = 0;
  +{abstract} void print(void) = 0;
  .. operator << ..
  std::cout << node.eval();
}
abstract Infix {
  .. members ..
  +~Infix(void);
  .. public ..
  +void set_left(int);
  +void set_right(int);
  +TreeNode &get_left(void);
  +TreeNode &get_right(void);
  .. protected ..
  TreeNode	*left;
  TreeNode	*right;
}
note right of Infix::~Infix
  Free left and right tree nodes
end note

class Add {
  .. public ..
  +int eval(void);
  +void print(void);
}
note right of Add::eval
  left->eval() + right->eval()
end note

class Number {
  .. public ..
  +void print(void);
  +void set_number(int);
  +int eval(void);
  .. private ..
  int	_number;
}

TreeNode <|-- Infix
TreeNode <|-- Number
Infix <|-- Add

@enduml
....
