= Assets
:nofooter:

[plantuml, target=token_id, format=svg, width=100%]
....
@startuml
skinparam defaultFontName JetBrains Mono

[*] --> ID
ID --> [*]
ID : char { char, digit, '-' } 

ID -> ID

@enduml
....

[plantuml, target=token_integer, format=svg, width=100%]
....
@startuml
skinparam defaultFontName JetBrains Mono

[*] --> integer
integer --> [*]
integer : char { digit }

integer -> integer

@enduml
....

[plantuml, target=class_integer, format=svg, width=100%]
....
@startuml
skinparam defaultFontName JetBrains Mono

class Integer {
  int 457
}

@enduml
....

[plantuml, target=class_id, format=svg, width=100%]
....
@startuml
skinparam defaultFontName JetBrains Mono

class Id {
  string "value"
}

@enduml
....

[plantuml, target=abstract_treenode, format=svg, width=100%]
....
@startuml
skinparam defaultFontName JetBrains Mono

abstract TreeNode

@enduml
....

[plantuml, target=class_add, format=svg, width=100%]
....
@startuml
skinparam defaultFontName JetBrains Mono

class add {
  treeNode	*left;
  treeNode	*right;
}

@enduml
....

[plantuml, target=class_subtract, format=svg, width=100%]
....
@startuml
skinparam defaultFontName JetBrains Mono

class subtract {
  treeNode	*left;
  treeNode	*right;
}

@enduml
....

[plantuml, target=class_mult, format=svg, width=100%]
....
@startuml
skinparam defaultFontName JetBrains Mono

class mult {
  treeNode	*left;
  treeNode	*right;
}

@enduml
....

[plantuml, target=class_div, format=svg, width=100%]
....
@startuml
skinparam defaultFontName JetBrains Mono

class  div {
  treeNode	*left;
  treeNode	*right;
}

@enduml
....

[plantuml, target=class_negate, format=svg, width=100%]
....
@startuml
skinparam defaultFontName JetBrains Mono

class negate {
  treeNode	*arg;
}

@enduml
....
